# Generated by Django 2.1.7 on 2019-03-30 22:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=django.utils.timezone.now, max_digits=7),
            preserve_default=False,
        ),
    ]
